title: ScanGov
description: Government digital service monitor
url: https://scangov.com
org: ScanGov
org-url: https://scangov.com
repo: https://github.com/scangov/scangov-com
rss: https://docs.scangov.org/feed.xml

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
    
# Social

github-url: https://github.com/scangov
linkedin-url: https://www.linkedin.com/company/scangov

# Date/time
date: "%B %-d, %Y"
timezone: America/Los_Angeles

# Collections
collections:
  pages:
    output: true
    permalink: /:title/

# Defaults
defaults:
  - scope:
      path: _pages
      type: pages
    values:
      layout: default

# Exclude
exclude:
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - google10895162be5e592f.html