docs_list_title: services
docs:

- title: Consulting
  icon: fa-solid fa-brain
  cta-text: Contact us
  cta-url: https://docs.google.com/forms/d/e/1FAIpQLSeKiSG0f07leAwW1QqIMSoDIgTA92m0jVy6NADtiaoPhg4rww/viewform
  checks:
    - Hourly
    - Project
    - Retainer

- title: Training
  icon: fa-solid fa-graduation-cap
  cta-text: Contact us
  cta-url: https://docs.google.com/forms/d/e/1FAIpQLSeKiSG0f07leAwW1QqIMSoDIgTA92m0jVy6NADtiaoPhg4rww/viewform
  checks:
    - Topical
    - Curriculum

